name: binary_conversion
description: A lightweight Dart package providing utility functions for converting numbers between common numeral systems (binary, octal, decimal, and hexadecimal).
version: 0.0.1
repository: https://github.com/da578/binary_conversion

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0 